version: "3.9"

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "mipt"
      POSTGRES_PASSWORD: "mipt"
  app:
    image: perovg/banking-system-application:v.10
    container_name: app
    depends_on:
      - postgres
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres"
      - "SPRING_DATASOURCE_USERNAME=mipt"
      - "SPRING_DATASOURCE_PASSWORD=mipt"
      - "SPRING_JPA_HIBERNATE_DDL_AUTO=update"
    ports:
      - "3691:8080"
